<p class="codepen" data-height="300" data-default-tab="html,result" data-slug-hash="wvYbYMP" data-user="Ruk47" style="height: 300px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;">
  <span>See the Pen <a href="https://codepen.io/Ruk47/pen/wvYbYMP">
  ğŸ¥¥Hazy ğŸŒ´</a> by Ruk47 (<a href="https://codepen.io/Ruk47">@Ruk47</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>